{
 "title": "Job Scheduler - Tasks",
 "tags": [ "job-scheduler" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tasks Created (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(job_scheduler_created_tasks_total)",
     "legendFormat": "created_total"
    }
   ]
  },
  {
   "title": "Tasks Completed (total)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(job_scheduler_completed_tasks_total)",
     "legendFormat": "completed_total"
    },
    {
     "expr": "job_scheduler_completed_tasks_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Created and Completed Tasks Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(job_scheduler_created_tasks_total)",
     "legendFormat": "created_tasks_total"
    },
    {
     "expr": "sum(job_scheduler_completed_tasks_total)",
     "legendFormat": "completed_tasks_total"
    }
   ]
  },
  {
   "title": "Average Task Execution Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "(job_scheduler_task_execution_time_seconds_sum / job_scheduler_task_execution_time_seconds_count)",
     "legendFormat": "AVG execution time({{instance}})"
    }
   ]
  }
 ]
}