CREATE TABLE IF NOT EXISTS public.tasks
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 NO MAXVALUE CACHE 1 ),
    next_execution_time timestamp(6) with time zone,
    name character varying(255),
    status character varying(255),
    trace_id UUID,
    CONSTRAINT tasks_pkey PRIMARY KEY (id)
)